# -*- coding: utf-8 -*-
"""Ezra + Iman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSWqYkfhI7al6qfmvwTOrv-OPwIfi1eI
"""

# Imports
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
import numpy as np

# Section 1
pitstopData = 'f1_pitstops_2018_2024.csv'
laptimePredictionColumn = ('Lap Time Variation') # will need to alter

topTeams = ['Ferrari', 'Redbull', 'McLaren', 'Mercedes','Renault'] # Equal number of teams
lowerTeams = ['Williams', 'Sauber', 'Haas F1 Team','Toro Rosso','Force India']

#debug code
df = pd.read_csv(pitstopData)
print(df)

# Section 2
try:
  df = pd.read_csv(pitstopData)
  print(f"✓ Loaded {len(df)} rows from CSV")

except FileNotFoundError:
  print("\nApologies, file was not found")
  exit()

print(df)

originalRowSize = len(df)
df = df.dropna(subset = laptimePredictionColumn)

reducedRows = originalRowSize - len(df) # this is the original minus the row of laptime prediction
if reducedRows < 0:
  print("\n Missing data, please check source file") # this is an error with the file

dataToUseColumn = ['Stint Length', 'Air_Temp_C', 'Track_Temp_C', 'Tire Compound', 'Constructor']

dfClean = df[dataToUseColumn + [laptimePredictionColumn]].copy() # iniitialise data to clean

def obtainTeamTier(constructor_name):
  if constructor_name in topTeams: # Checks if it is ferrari, merc, mclaren or redbull
    return 'Top_Tier'
  else:
    return 'Other_Tier' # comparator other condition

dfClean['Team_Catagory'] = dfClean['Constructor'].apply(obtainTeamTier) # above function cqlled
dfClean = dfClean.drop('Constructor', axis = 1)

dfEncoded = pd.get_dummies(dfClean, columns = ['Tire Compound', 'Team_Catagory'], drop_first = False)

xColumns = [col for col in dfEncoded.columns if col not in [laptimePredictionColumn, 'Team_Catagory_Other_Tier']] # final essentails for columns in x axis
xAxis = dfEncoded[xColumns]
yAxis = dfEncoded[laptimePredictionColumn]
print(f"\nUsing {len(xColumns)} and these column features {xColumns}")

xTrain, xTest, yTrain, yTest = train_test_split(xAxis, yAxis, test_size = 0.3, random_state = 15)
print(f"\nUsing {len(xTrain)} number of samples, the test set has {len(xTest)} number of samples.")

# Section 3

#unifiedModel = DecisionTreeRegressor(random_state = 15)
unifiedModel = DecisionTreeRegressor(random_state=15, max_depth=5, min_samples_split=10)  #max depth to limit depth of tree and prevent overfitting, min samples to split an internal node,higher value rpevents from splitting node to early


unifiedModel.fit(xTrain, yTrain)
unifiedPredictions = unifiedModel.predict(xTest)

testResults = xTest.copy()
testResults['actual'] = yTest
testResults['predicted'] = unifiedPredictions
testResults['team_tier'] = np.where(testResults['Team_Catagory_Top_Tier'] == 1, 'Top_Tier', 'Other_Tier') # human readable tier list on the datasheet

topTierMAE = mean_absolute_error(
    testResults[testResults['team_tier'] == 'Top_Tier']['actual'],
    testResults[testResults['team_tier'] == 'Top_Tier']['predicted'] # actual value vs predicted
)

lowerTierMAE = mean_absolute_error(
    testResults[testResults['team_tier'] == 'Other_Tier']['actual'],
    testResults[testResults['team_tier'] == 'Other_Tier']['predicted'] # actual value vs predicted
)

biasAmount = abs(topTierMAE - lowerTierMAE) # core metric for unfairness this is the difference in mean absolute error where bias between smples in either team can be found

print(f"top tie MAE is {topTierMAE:.4f}") # top mean abs error value
print(f"lower tier MAE is {lowerTierMAE:.4f}") # lower mean abs error value

print(f"the difference in MAE is {biasAmount:.4f}") # unfair

if lowerTierMAE > topTierMAE:
  print("The predictions are geared towards top tier teams.")
else:
  print("The predictions are geared towards lower tier teams.")

# next step is for training seperate specialised (section 4)

#Section 4
trainData = xTrain.copy()
trainData['target'] = yTrain

#split training by team tier
topTier_train = trainData[trainData['Team_Catagory_Top_Tier'] == 1] #filters the training data to include only top-tier samples
lowerTier_train = trainData[trainData['Team_Catagory_Top_Tier'] == 0] #filters the training data toinclude only lower-tier samples

print(f"Top-tier training samples: {len(topTier_train)}") #size of top-tier training data
print(f"Low-tier training samples: {len(lowerTier_train)}") #size of lower-tier training data

#Features for specialized models
specialisedFeatures = [col for col in trainData.columns #defines the final list of inputs for the two new models.
                       if col not in ['target', 'Team_Catagory_Top_Tier', 'Team_Catagory_Other_Tier']] #excludes the team catgory

#train model for top tier teams
xTop = topTier_train[specialisedFeatures]  #inputs for the top-tier model
yTop = topTier_train['target'] #target for the top tier model
#modelTop = DecisionTreeRegressor(random_state = 42) #creates top tier model object
modelTop = DecisionTreeRegressor(random_state=42, max_depth=5, min_samples_split=10) #try with 5
modelTop.fit(xTop, yTop) # AI learning step: trains model top only on top tier data

#train model for low tier teams
xLower = lowerTier_train[specialisedFeatures]  #inputs for the lower-tier model
yLower = lowerTier_train['target'] #target for the lower tier model
#modelLower = DecisionTreeRegressor(random_state = 42) #creates lower tier model object
modelLower = DecisionTreeRegressor(random_state=42, max_depth=5, min_samples_split=10)#try with 5
modelLower.fit(xLower, yLower) # AI learning step: trains model lower only on top tier data

print("Trained both specialised models")

#Test the specialized model
testFeatures = testResults[specialisedFeatures] #gets the common input features for prediction

#apply the right model to each test sample
specialisedPred =  [] #empty list to store the predictions
for idx, row in testResults.iterrows(): #loops thru every single row(lap) in the test data
    if row['team_tier'] == 'Top_Tier': #checks if the team is top tier
       pred = modelTop.predict(testFeatures.loc[idx:idx])[0] #if yes, uses the top tier model for prediction
    else:
       pred = modelLower.predict(testFeatures.loc[idx:idx])[0]
    specialisedPred.append(pred) #adds the prediction to the list

testResults['specializedPred'] = specialisedPred #adds the final list of predictions to the test results Dataframe

# We considered that 2018 to 2024 was a really large range and we wanted to see if we could get the actual bias based on each season
# Lets check against seasons as
# Directional error analysis (bias direction, not magnitude)
testResults['error_specialised'] = (
    testResults['specializedPred'] - testResults['actual']
)

directionBias = testResults.groupby('team_tier')['error_specialised'].mean()

print(f"This is the directional bias of top teams versus the other teams")
print(directionBias)

#Calculate new MAE values
topTierMAESpecialised = mean_absolute_error(
    testResults[testResults['team_tier'] == 'Top_Tier']['actual'],
    testResults[testResults['team_tier'] == 'Top_Tier']['specializedPred']
    )

lowerTierMAESpecialised = mean_absolute_error(
    testResults[testResults['team_tier'] == 'Other_Tier']['actual'],
    testResults[testResults['team_tier'] == 'Other_Tier']['specializedPred']
)

biasAmountSpecialised = abs(topTierMAESpecialised - lowerTierMAESpecialised)

print(f"top tier MAE is {topTierMAESpecialised:.4f}") # top mean abs error value
print(f"lower tier MAE is {lowerTierMAESpecialised:.4f}") # lower mean abs error value
print(f"the difference in MAE is {biasAmountSpecialised:.4f}") # unfair

# Section 5 + 6 (final calculations and plotting)

#Final report for the value comparison

print("The final results can be found below:")

comparisonDF = pd.DataFrame({'Team Group': ['Top teams', 'Other teams', 'The Bias'],
                             'Unified Models': [topTierMAE, lowerTierMAE, biasAmount], #OG data
                             'Specialised Models': [topTierMAESpecialised, lowerTierMAESpecialised, biasAmountSpecialised]
})

biasReduction = ((biasAmount - biasAmountSpecialised) / biasAmount) * 100 if biasAmount > 0 else 0 # always looks for greater or equal to zero

print(comparisonDF.to_string(index = False, float_format = '%.4f')) # no index and to 4 dp
print(f'Bias Reduction: {biasReduction:.1f} %.')

if biasAmountSpecialised < biasAmount:
  print('Successful attempt for specialised model.')
else:
  print('Specialised model not successful')

# visual aspect with plotting

fig, ax = plt.subplots(figsize = (10, 10))

labels = ['Unified\nTop Teams', 'Specialised\nTop Teams', 'Unified\nOther Teams', 'Specialised\nOther Teams']

unifiedAndSpecialisedErrors = [topTierMAE, lowerTierMAE, topTierMAESpecialised, lowerTierMAESpecialised]
colours = ['purple', 'pink', 'purple', 'pink']

xPosition = np.arange(4)
width = 0.5

bars = ax.bar(xPosition, unifiedAndSpecialisedErrors, width, color = colours, alpha=0.6)

ax.set_xlabel('Team groupings')
ax.set_ylabel('MAE (mean absolute error)')
ax.set_title('Unified vs Specialised Models for Bias')
ax.set_xticks(xPosition)
ax.set_xticklabels(labels)
ax.legend()
ax.grid(True, alpha = 0.2)

for bar in bars:
   height = bar.get_height()
   ax.text(bar.get_x() + (bar.get_width() / 2), height,
                     f'{height:.4f}', ha = 'center', va = 'bottom', fontsize = 12)

plt.tight_layout()
plt.show()

print('Predicition plotting complete')