# -*- coding: utf-8 -*-
"""Salma&Momena.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YrepgM7VP3T-4hXfC9mOl6Fd8JEhCkvQ
"""

#Section 1

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv("f1_pitstops_2018_2024.csv")
data.head()  # we do this to read the data

data.info() #we do this to see if we have any null values
data.dropna(inplace=True) #returns data with only non-null values, (drops rows with missing stuff)

data.info() #reload the new data

TARGET_COLUMN = 'Lap Time Variation'   # the thing we want to predict (change name if needed)
CONSTRUCTOR_COL = 'Constructor'        # column that holds the team name
DATA_PATH = "f1_pitstops_2018_2024.csv"
   # path to the CSV file

TOP_TEAMS = ["Mercedes" , "Ferrari", "Red Bull"]


OTHER_TEAMS = ["Sauber", "Toro Rosso", "Haas F1 Team", "Williams", "Force India", "Renault", "AlphaTauri", "Aston Martin", "McLaren", "Alpine", "Alpine", "Racing Point", "Visa Cash App R8 F1 Team", "Stake F1 Team Kick Sauber"]

def get_team_tier(team):
    if team in TOP_TEAMS:
        return "Top_Tier"
    return "Other_Tier"

#Section 2-Loading and cleaning the data

print("Loading data")

LAPS_BEFORE_df = pd.read_csv(DATA_PATH)
print(f"Data loaded: {LAPS_BEFORE_df.shape[0]:,} rows and {LAPS_BEFORE_df.shape[1]} columns.")

print("\nData set columns:")
print(LAPS_BEFORE_df.columns.tolist())

# get rid of missing target values
before_rows = len(LAPS_BEFORE_df)
raw_laps_df = LAPS_BEFORE_df.dropna(subset=[TARGET_COLUMN]).copy()
after_rows = len(raw_laps_df)
dropped_target = before_rows - after_rows

print(f"\nRemoved {dropped_target} laps where '{TARGET_COLUMN}' was missing.")
print(f"Remaining laps: {after_rows:,}")

# pick my features
feature_columns = ["Stint Length", "Air_Temp_C", "Tire Compound", "Constructor"]

print("\nFeatures:")
print(feature_columns)

# grab just the columns i need
clean_laps_df = raw_laps_df[feature_columns + [TARGET_COLUMN]].copy()

# remove rows with missing data
clean_laps_df = clean_laps_df.dropna(subset=["Stint Length", "Air_Temp_C"])

print("\nFirst few rows:")
print(clean_laps_df.head())

# add team category
team_cats = []
for team in clean_laps_df["Constructor"]:
    team_cats.append(get_team_tier(team))
clean_laps_df["Team_Category"] = team_cats

clean_laps_df = clean_laps_df.drop(columns=["Constructor"])

# turn categories into numbers
laps_encoded = pd.get_dummies(clean_laps_df, columns=["Tire Compound", "Team_Category"], drop_first=False)

print("\nColumns after encoding:")
print(laps_encoded.columns.tolist())

# split into inputs and target
feature_columns = []
for col in laps_encoded.columns:
    if col != TARGET_COLUMN:
        feature_columns.append(col)

X = laps_encoded[feature_columns]
y = laps_encoded[TARGET_COLUMN]

print(f"\nX has {X.shape[0]:,} rows and {X.shape[1]} features.")
print(f"y has {len(y):,} values.")

# split into training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=10)

print(f"\nTraining set: {X_train.shape[0]:,} laps")
print(f"Test set: {X_test.shape[0]:,} laps")

#SECTION 3: Bias proof (unified model)

# make model
unified_model = DecisionTreeRegressor(random_state=42, max_depth=6, min_samples_leaf=20)
unified_model.fit(X_train, y_train)

print("Completed training")

# predictions
preds = unified_model.predict(X_test)

# results table
results = X_test.copy()
results["Actual"] = y_test.values
results["Predicted"] = preds

# team tier column
results["Team_tier"] = np.where(
    results["Team_Category_Top_Tier"] == 1,
    "Top_Tier",
    "Other_Tier")

print("Added teams")

print("\nFirst rows:")
print(results[["Actual", "Predicted", "Team_tier"]].head())

# top tier mae
top_actual = []
top_pred = []
for i in results.index:
    if results.loc[i, "Team_tier"] == "Top_Tier":
        top_actual.append(results.loc[i, "Actual"])
        top_pred.append(results.loc[i, "Predicted"])

top_mae = mean_absolute_error(top_actual, top_pred)

# other tier mae
other_actual = []
other_pred = []
for i in results.index:
    if results.loc[i, "Team_tier"] == "Other_Tier":
        other_actual.append(results.loc[i, "Actual"])
        other_pred.append(results.loc[i, "Predicted"])

other_mae = mean_absolute_error(other_actual, other_pred)

# bias
diff = top_mae - other_mae
if diff < 0:
    diff = diff * -1

avg = (top_mae + other_mae) / 2
pct = (diff / avg) * 100

total = mean_absolute_error(results["Actual"], results["Predicted"])

print("\nSummary")
print("Top tier MAE:", top_mae)
print("Other tier MAE:", other_mae)
print("Average MAE:", total)
print("Bias:", diff)
print("Bias percent:", pct)

if pct < 5:
    print("Very small bias")
if pct >= 5 and pct < 20:
    print("Moderate bias")
if pct >= 20:
    print("High bias")

if other_mae > top_mae:
    print("Worse for other teams")
if top_mae > other_mae:
    print("Worse for top teams")
if top_mae == other_mae:
    print("Same for both")

test_results = results.copy()


# Unified model MAE calculations (needed for Section 6)
top_tier_mae = top_mae     # from the unified model results
other_tier_mae = other_mae # from the unified model results

# Unified model bias
bias_amount = abs(top_tier_mae - other_tier_mae)

#Section 4


TEAM_COLUMN = "Team_Category_Top_Tier"  # ← ADD THIS LINE (only new line you need)

 #We combine X_train + y_train so we can filter by top teams

train_data = pd.concat([X_train, y_train], axis=1) #combines X_train and y_train columns into 1 table side by side (axis=1=side by side column wise, axis=0= row wise)

#we are splitting only the training data into top tier and other tier groups using yes for teop teams and no for other teams
df_top_train = train_data[train_data[TEAM_COLUMN] == 1 ] #we are filtering the train_data and creating a new daa_table for just top teams and just other teams
df_other_train = train_data[train_data[TEAM_COLUMN] == 0]

print("\nTop-team training rows:", df_top_train.shape[0])
print("Other-team training rows:", df_other_train.shape[0])

#Split each group into new X (inputs) and y (target)

#TOP TEAMS
X_top_train = df_top_train.drop(columns=[TARGET_COLUMN]) #we drop the lap time variation as this is not an input it is something we want the AI to predict
y_top_train = df_top_train[TARGET_COLUMN] #this is the target value we want the AI to predict for our teams



X_top_train.head() #shows the data set with the columns selected dropped

X_top_train.shape
y_top_train.shape


#OTHER TEAMS

X_other_train= df_other_train.drop(columns=[TARGET_COLUMN]) #we drop the lap time variation as this is not an input it is something we want the AI to predict
y_other_train = df_other_train[TARGET_COLUMN] #this is the target value we want the AI to predict for our teams


X_other_train.head() #shows the data set with the columns selected dropped
X_other_train.shape
y_other_train.shape


#Train 2 separate models

rg1 = DecisionTreeRegressor(max_depth=6, min_samples_leaf=20, random_state=42)
 #Model trained ONLY on top teams
rg1.fit(X_top_train, y_top_train)

rg2 = DecisionTreeRegressor(max_depth=6, min_samples_leaf=20, random_state=42)
rg2.fit(X_other_train, y_other_train)   #Model trained ONLY on other teams



#Prepare test data (combine X_test and y_test)

test_data = pd.concat([X_test, y_test], axis=1)




#split test data into top and other

df_top_test = test_data[test_data[TEAM_COLUMN] == 1]
print(df_top_test.shape)
df_top_test.head()

df_other_test = test_data[test_data[TEAM_COLUMN] == 0]
print(df_other_test.shape)
df_other_test.head()


#prepare x and y for top team test set

X_top_test = df_top_test.drop(columns=[TARGET_COLUMN])
y_top_test = df_top_test[TARGET_COLUMN]

X_top_test.head()
X_top_test.shape
y_top_test.shape

#prepare x and y for other teams test set

X_other_test = df_other_test.drop(columns=[TARGET_COLUMN])
y_other_test = df_other_test[TARGET_COLUMN]

X_other_test.head()
X_other_test.shape
y_other_test.shape


#Predict using the trained models

y_predict_top = rg1.predict(X_top_test)

y_predict_other = rg2.predict(X_other_test)


# SPECIALISED model errors (two-model setup)
top_tier_mae_specialised = mean_absolute_error(y_top_test, y_predict_top)
other_tier_mae_specialised = mean_absolute_error(y_other_test, y_predict_other)

print("----- Specialised Models (Two Models) -----")
print(f"Top Tier MAE (specialised):   {top_tier_mae_specialised:.4f}")
print(f"Other Tier MAE (specialised): {other_tier_mae_specialised:.4f}")

# SECTION 5 — Mitigation evaluation (specialised model bias)

new_bias = abs(top_tier_mae_specialised - other_tier_mae_specialised)

print("New Bias:", new_bias)
print(f"New Bias (two models): {new_bias:.4f}")

if top_tier_mae_specialised < other_tier_mae_specialised:
    print("Specialised model predicts better for TOP teams.")
elif top_tier_mae_specialised > other_tier_mae_specialised:
    print("Specialised model predicts better for OTHER teams.")
else:
    print("Both groups have equal error — perfectly fair model.")

#Section 6

print("\n")

print("Section 6: compare one model vs two models")

print("\n")


# 1. show a simple comparison table

groups = ["Top_Tier", "Other_Tier"]

unified_mae_list = [top_tier_mae, other_tier_mae]

special_mae_list = [top_tier_mae_specialised, other_tier_mae_specialised]


print("Group        Unified_MAE    Specialised_MAE")

print(groups[0], "   ", round(unified_mae_list[0], 4), "        ", round(special_mae_list[0], 4))

print(groups[1], "   ", round(unified_mae_list[1], 4), "        ", round(special_mae_list[1], 4))


# 2. work out bias before and after

old_bias = bias_amount

new_bias = top_tier_mae_specialised - other_tier_mae_specialised

if new_bias < 0:

    new_bias = new_bias * -1


# 3. percentage change in bias

bias_change_pct = 0

if old_bias != 0:

    bias_change_pct = (old_bias - new_bias) / old_bias

    bias_change_pct = bias_change_pct * 100


print("\nOld bias (unified model):", old_bias)

print("New bias (specialised models):", new_bias)

print("Bias change:", round(bias_change_pct, 2), "%")


# 4. say if it got better or worse

if new_bias < old_bias:

    print("Specialised models reduced the bias")

elif new_bias > old_bias:

    print("Specialised models increased the bias")

else:

    print("Bias stayed the same")


# positions for the two groups on x-axis

pos_top = 0

pos_other = 1

width = 0.35


# positions for unified and specialised bars

pos_top_unified = pos_top - width/2

pos_top_special = pos_top + width/2

pos_other_unified = pos_other - width/2

pos_other_special = pos_other + width/2


plt.figure()


# draw each bar

plt.bar(pos_top_unified, unified_mae_list[0], width, label="Unified",color="tab:blue")

plt.bar(pos_top_special, special_mae_list[0], width, label="Specialised", color="tab:orange")

plt.bar(pos_other_unified, unified_mae_list[1], width,color="tab:blue")

plt.bar(pos_other_special, special_mae_list[1], width,color="tab:orange")


plt.xticks([pos_top, pos_other], groups)

plt.xlabel("Group")

plt.ylabel("MAE")

plt.title("Unified vs Specialised models")


# add MAE numbers on top of bars

plt.text(pos_top_unified, unified_mae_list[0], str(round(unified_mae_list[0], 3)), ha='center')

plt.text(pos_top_special, special_mae_list[0], str(round(special_mae_list[0], 3)), ha='center')

plt.text(pos_other_unified, unified_mae_list[1], str(round(unified_mae_list[1], 3)), ha='center')

plt.text(pos_other_special, special_mae_list[1], str(round(special_mae_list[1], 3)), ha='center')


plt.legend()

plt.show()